protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    public $layout = '//layouts/column1';
    public $showAll = false;

    /**
     * Declares class-based actions.
     */
    public function actions()
    {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
                //'testLimit' => 0,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'successfullyAdded', 'dealerCarAnnouncements', 'personalPage', 'forgotPassword', 'officialDealers', 'universalDealers', 'activateForgotPassword', 'getRates', 'loadMyAnnouncements', 'myAnnouncements', 'authenticateUser', 'activateUser', 'succeedRegistered', 'auto', 'sparePart', 'autoRent', 'ruralTech', 'taxi', 'shipping', 'addAnnouncement', 'jobList', 'carRepair', 'login', 'needRegister',
                    'registration', 'news', 'loadUploads', 'view', 'select', 'create', 'captcha', 'edit', 'test2', 'trainingCar', 'evacuator', 'jobForm', 'addUser', 'listTaxiAnnouncements',
                    'changeLanguage', 'listCarAnnouncements', 'carDetailed', 'searchByFilters', 'getCarAnnouncementsByFilters', 'listCarAnnouncementsAll', 'listJobAnnouncementsAll',
                    'newsDetailed', 'appa', 'customs', 'tech', 'roadPoliceAddresses', 'autoSchool', 'generateCaptcha', 'captcha', 'listCarWheelAnnouncementsAll', 'listRuralAnnouncementsAll',
                    'listSparePartAnnouncementsAll', 'listSparePartAnnouncements', 'listRentCarAnnouncements', 'autoService', 'listEvacuatorAnnouncementsAll', 'listEvacuatorAnnouncements', 'listShippingAnnouncements', 'tourism', 'listTransportationAnnouncements',
                    'transportation', 'listTourismAnnouncements', 'wheelDetailed', 'sparePartDetailed', 'carRentDetailed', 'taxiDetailed', 'listSpecCarAnnouncements',
                    'evacuatorDetailed', 'shippingDetailed', 'transportationDetailed', 'tourismDetailed', 'ruralTechDetailed', 'jobDetailed', 'specCarDetailed', 'editForm',
                    'listAutoServices', 'autoServiceDetailed', 'getDealerCarAnnouncements', 'roadPolicePenalty', 'roadSigns', 'trafficRules', 'selectedServices',
                    'listServicesByPlace', 'listAutoServicesFromPlace', 'listAutoServicesFromSubPlace', 'getDealerMarker', 'siteRules', 'addValidDate'),
                'users' => array('*'),
            ),
        );
    }

    /** =========================================== START VIEW ACTION ===================================================== */
    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex()
    {
        $this->layout_top_bar = '//layouts/top_bar_1';
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
        $this->render('index', array('detail_url' => 'site/carDetailed'));
    }

    public function actionSuccessfullyAdded()
    {
        //$this->layout_top_bar = '//layouts/top_bar_1';
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
        $this->render('successfullyAdded', array('detail_url' => 'site/carDetailed'));
    }


    public function actionForgotPassword()
    {
        //$this->layout_top_bar = '//layouts/top_bar_1';
        // renders the view file 'protected/views/site/index.php'
        // using the default layout 'protected/views/layouts/main.php'
        $this->render('forgotPassword');
    }


    public function actionAuto()
    {
        $this->layout_top_bar = '//layouts/top_bar_1';
        $captcha = new MyCaptcha();
        $this->render('auto_form', array("editMode" => 0,  'captcha' => $captcha, 'editMode2' => false, "announcementId" => 0, "formCaption" => Messages::getMessage(18)));
    }

    private function checkPermissions($model, $id)
    {
        $user_id = $model->findByPk($id)->user_id;
        if ($user_id === Yii::app()->user->id) {
            return true;
        }
        return false;
    }

    private function expandValidDate(&$announcement, $term_id)
    {
        $currentDate = date('Y-m-d');
        if ($term_id == 57) { //1 week
            if ($announcement->validDate == null || $announcement->validDate == 'null' || $announcement->validDate == "") {
                $announcement->validDate = date('Y-m-d', strtotime($currentDate) + (24 * 3600 * 7));
                $announcement->save();
            } else {
                $announcement->validDate = date('Y-m-d', strtotime($announcement->validDate) + (24 * 3600 * 7));
                $announcement->save();
            }
        } else if ($term_id == 58) { //2 week
            if ($announcement->validDate == null || $announcement->validDate == 'null' || $announcement->validDate == "") {
                $announcement->validDate = date('Y-m-d', strtotime($currentDate) + (24 * 3600 * 14));
                $announcement->save();
            } else {
                $announcement->validDate = date('Y-m-d', strtotime($announcement->validDate) + (24 * 3600 * 14));
                $announcement->save();
            }
        } else if ($term_id == 59) { //3 week
            if ($announcement->validDate == null || $announcement->validDate == 'null' || $announcement->validDate == "") {
                $announcement->validDate = date('Y-m-d', strtotime($currentDate) + (24 * 3600 * 21));
                $announcement->save();
            } else {
                $announcement->validDate = date('Y-m-d', strtotime($announcement->validDate) + (24 * 3600 * 21));
                $announcement->save();
            }
        } else if ($term_id == 3372) { //30 days
            if ($announcement->validDate == null || $announcement->validDate == 'null' || $announcement->validDate == "") {
                $announcement->validDate = date('Y-m-d', strtotime($currentDate) + (24 * 3600 * 30));
                $announcement->save();
            } else {
                $announcement->validDate = date('Y-m-d', strtotime($announcement->validDate) + (24 * 3600 * 30));
                $announcement->save();
            }
        } else if ($term_id == 3373) { //60 days
            if ($announcement->validDate == null || $announcement->validDate == 'null' || $announcement->validDate == "") {
                $announcement->validDate = date('Y-m-d', strtotime($currentDate) + (24 * 3600 * 60));
                $announcement->save();
            } else {
                $announcement->validDate = date('Y-m-d', strtotime($announcement->validDate) + (24 * 3600 * 60));
                $announcement->save();
            }
        } else if ($term_id == 3374) { //120 days
            if ($announcement->validDate == null || $announcement->validDate == 'null' || $announcement->validDate == "") {
                $announcement->validDate = date('Y-m-d', strtotime($currentDate) + (24 * 3600 * 120));
                $announcement->save();
            } else {
                $announcement->validDate = date('Y-m-d', strtotime($announcement->validDate) + (24 * 3600 * 120));
                $announcement->save();
            }
        }
    }

    public function  actionAddValidDate()
    {
        $id = $_POST['id'];
        $formType = $_POST['formType'];
        $term_id = $_POST['term_id'];

        switch ($formType) {
            case "1":
                $announcement = CarAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "2":
                $announcement = CarRentAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "3":
                $announcement = WheelsAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "4":
                $announcement = SparePartAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "5":
                $announcement = RuraltechAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "6":
                $announcement = ShippingAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "7":
                $announcement = TransportationAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "8":
                $announcement = TouristAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "9":
                $announcement = EvacuatorAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "10":
                $announcement = JobAnnouncement::model()->findByPk($id);
                $this->expandValidDate($announcement, $term_id);
                break;
            case "11":

protected/views/site/_customs.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edgar
 * Date: 8/5/13
 * Time: 12:00 AM
 * To change this template use File | Settings | File Templates.
 */
?>

<div class="left" ng-controller="customs_view_controller" ng-init="init();">

    <div class="middle_panel left decoration" style="margin-top: 25px;width: 770px !important;min-height: 500px;" cg-busy="{promise:promise,message:'loading',backdrop:true}">
        <div class="title">
            <h3> Таможенная</h3>
        </div>
        <div class="news_description"  style="padding: 15px;" ng-bind-html="tax_item.text | unsafe">
        </div>

    </div>

    <div style="clear: both"></div>
    <div style="margin-left: 5px">
        <google-map center="center" draggable="true" zoom="zoom" markers="markers"
                    class="angular-google-map"  style="height: 400px;width: 760px;"></google-map>
    </div>

</div>



<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-controllers/customs_view_controller.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-models/services.js"></script>

protected/views/site/_detailedCarRent.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edgar
 * Date: 10/2/13
 * Time: 11:55 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<div ng-class="ng-cloak">
<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/right_carusel.css"/>
<?php Yii::app()->getClientScript()->registerScriptFile(Yii::app()->request->baseUrl . '/js/jquery.carouFredSel.js'); ?>
<div style="display: none" id="car_id"><?php echo $car_id ?> </div>

<div class="announcement_field" ng-controller="carRentDetailedController" ng-init="initIt();"
     cg-busy="{promise:promise,message:'loading',backdrop:true}">
    <div class="announcement_field_left left selected_car_info_block decoration">
        <div class="title">
            <h3 style="float: left"><?php echo Messages::getMessage(122) ?></h3>
            <h3 style="float: right"><?php echo Messages::getMessage(191) ?> - {{announcement.view_count}}</h3>
        </div>

        <div class="car_description_banner" style="height: 25px;padding: 5px;margin-bottom: 10px;">
            <div style="font-size: 18px;color: red;float: left">ID {{ announcement.id }}</div>
            <div style="cursor: pointer;float: right">
                <img src="images/remember_plus.png " ng-show="!remembered" ng-click="addToRememberedList(announcement.id, announcement.announcement_name, announcement.payment_type+' '+announcement.price, announcement.main_image, announcement.rate_id)">
                <img src="images/remember_minus.png " ng-show="remembered" ng-click="removeFromRememberedList(announcement.id, announcement.announcement_name, announcement.price, announcement.main_image)">
            </div>
        </div>

        <?php if($this->isAdmin()): ?>
            <div class="right" style="margin-right: 15px;margin-bottom: 10px" ng-hide="announcement.isAccepted">
                <a class="accept" ng-click="acceptItem(announcement.id, $event)">Accept</a>
                <a class="delete" style="width: 40px;" ng-click="deleteItem(announcement.id, $event)">Delete</a>
            </div>
        <?php endif ?>

        <div>
            <?php echo $this->renderPartial('detailed_left'); ?>
            <?php echo $this->renderPartial('detailed_main'); ?>
        </div>

    </div>


    <?php echo $this->renderPartial('//layouts/rememberedItems'); ?>


</div>

<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-controllers/detailedRentCar_controller.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-models/services.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/fancybox.js"></script>
</div>

protected/views/site/_detailedTaxi.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edgar
 * Date: 10/3/13
 * Time: 12:24 AM
 * To change this template use File | Settings | File Templates.
 */
?>

<div ng-class="ng-cloak">
<link href="http://stg.odnoklassniki.ru/share/odkl_share.css" rel="stylesheet">
<script src="http://stg.odnoklassniki.ru/share/odkl_share.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/right_carusel.css"/>
<?php Yii::app()->getClientScript()->registerScriptFile(Yii::app()->request->baseUrl . '/js/jquery.carouFredSel.js'); ?>
<div style="display: none" id="car_id"><?php echo $car_id ?> </div>

<div class="announcement_field" ng-controller="taxiDetailedController" ng-init="initIt();"
     cg-busy="{promise:promise,message:'loading',backdrop:true}">
    <div class="announcement_field_left left selected_car_info_block decoration">
        <div class="title">
            <h3 style="float: left"><?php echo Messages::getMessage(125) ?></h3>
            <h3 style="float: right"><?php echo Messages::getMessage(191) ?> - {{announcement.view_count}}</h3>
        </div>
        <div class="car_description_banner" style="height: 25px;padding: 5px;margin-bottom: 10px;">
            <div style="font-size: 18px;color: red;float: left">ID {{ announcement.id }}</div>
            <div style="cursor: pointer;float: right">
                <img src="images/remember_plus.png " ng-show="!remembered" ng-click="addToRememberedList(announcement.id, announcement.announcement_name, announcement.payment_type+' '+announcement.price, announcement.main_image, announcement.rate_id)">
                <img src="images/remember_minus.png " ng-show="remembered" ng-click="removeFromRememberedList(announcement.id, announcement.announcement_name, announcement.price, announcement.main_image)">
            </div>
        </div>
        <?php if($this->isAdmin()): ?>
            <div class="right" style="margin-right: 15px;margin-bottom: 10px" ng-hide="announcement.isAccepted">
                <a class="accept" ng-click="acceptItem(announcement.id, $event)">Accept</a>
                <a class="delete" style="width: 40px;" ng-click="deleteItem(announcement.id, $event)">Delete</a>
            </div>
        <?php endif ?>

        <div>
            <?php echo $this->renderPartial('detailed_left'); ?>

            <?php echo $this->renderPartial('detailed_main'); ?>
        </div>

    </div>

    <?php echo $this->renderPartial('//layouts/rememberedItems'); ?>


</div>

<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-controllers/detailedTaxi_controller.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-models/services.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/fancybox.js"></script>

</div>

protected/views/site/_detailedTourism.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edgar
 * Date: 10/6/13
 * Time: 10:10 PM
 * To change this template use File | Settings | File Templates.
 */
?>

<div ng-class="ng-cloak">
<link href="http://stg.odnoklassniki.ru/share/odkl_share.css" rel="stylesheet">
<script src="http://stg.odnoklassniki.ru/share/odkl_share.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/right_carusel.css"/>
<?php Yii::app()->getClientScript()->registerScriptFile(Yii::app()->request->baseUrl . '/js/jquery.carouFredSel.js'); ?>
<div style="display: none" id="car_id"><?php echo $car_id ?> </div>

<div class="announcement_field" ng-controller="tourismDetailedController" ng-init="initIt();"
     cg-busy="{promise:promise,message:'loading',backdrop:true}">
    <div class="announcement_field_left left selected_car_info_block decoration">
        <div class="title">
            <h3 style="float: left"><?php echo Messages::getMessage(129) ?></h3>
            <h3 style="float: right"><?php echo Messages::getMessage(191) ?> - {{announcement.view_count}}</h3>
        </div>
        <div class="car_description_banner" style="height: 25px;padding: 5px;margin-bottom: 10px;">
            <div style="font-size: 18px;color: red;float: left">ID {{ announcement.id }}</div>
            <div style="cursor: pointer;float: right">
                <img src="images/remember_plus.png " ng-show="!remembered" ng-click="addToRememberedList(announcement.id, announcement.announcement_name, announcement.price, announcement.main_image, announcement.rate_id)">
                <img src="images/remember_minus.png " ng-show="remembered" ng-click="removeFromRememberedList(announcement.id, announcement.announcement_name, announcement.price, announcement.main_image)">
            </div>
        </div>
        <?php if($this->isAdmin()): ?>
            <div class="right" style="margin-right: 15px;margin-bottom: 10px" ng-hide="announcement.isAccepted">
                <a class="accept" ng-click="acceptItem(announcement.id, $event)">Accept</a>
                <a class="delete" style="width: 40px;" ng-click="deleteItem(announcement.id, $event)">Delete</a>
            </div>
        <?php endif ?>

        <div>
            <?php echo $this->renderPartial('detailed_left'); ?>

            <?php echo $this->renderPartial('detailed_main'); ?>
        </div>

    </div>

    <?php echo $this->renderPartial('//layouts/rememberedItems'); ?>

</div>

<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-controllers/detailedTourism_controller.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-models/services.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/fancybox.js"></script>

</div>

protected/views/site/_listDealerAnnouncements.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edgar
 * Date: 12/5/13
 * Time: 12:22 AM
 * To change this template use File | Settings | File Templates.
 */
?>

<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />

<input type="hidden" id="dealer_id" value="<?php echo $dealer_id ?>">
<div class="middle_panel left decoration" style="margin-top: 25px;width: 770px !important;" ng-controller="dealerAnnouncements" ng-init="init();">

    <div class="title" style="margin-bottom: 10px;">
        <h3><?php echo Messages::getMessage(72) ?></h3>
        <h3 ng-click="switchToMap()" ng-show="gallery_view" style="cursor: pointer;float: right; margin-right: 15px;color: #ff0000;width: 120px;font-weight: bold">Картой</h3>
        <h3 ng-click="switchToGallery()" ng-show="map_view" style="cursor: pointer;float: right; margin-right: 15px;color: #ff0000;width: 120px;font-weight: bold">Բաներով</h3>

    </div>


    <div ng-show="gallery_view">
        <div style="clear: both"></div>
        <?php echo $this->renderPartial('dealerPhotoGallery', array('images'=>$dealerImages)); ?>
    </div>

    <span ng-show="map_view">
        <div style="clear: both"></div>
        <google-map center="center" refresh="map_view" draggable="true" zoom="zoom" markers="markers"
                    class="angular-google-map"  style="height: 350px;width: 750px;;margin-left: 10px;"></google-map>
    </span>

    <div class="left" ng-controller="dealerAnnouncements" ng-init="init();" style="width: 100%">
            <?php echo $this->renderPartial('_listTemplate',array('title'=>$title, 'detail_url'=>$detail_url, 'isDealerList'=>'true' , 'isCar' =>$isCar, 'banner'=>$this->banner)); ?>
    </div>



</div>

<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-controllers/dealer_announcements_controller.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-models/services.js"></script>

protected/views/site/_listRentCars.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edgar
 * Date: 8/24/13
 * Time: 10:43 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<div class="left" ng-controller="carRentAnnouncementsController" ng-init="init();">
    <div cg-busy="{promise:promise,message:'loading',backdrop:true,}" style="height: 700px;">

        <?php echo $this->renderPartial('_listTemplate',array('title'=>$title, 'detail_url'=>$detail_url , 'isCar' =>$isCar )); ?>

    </div>
</div>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-controllers/listRentCarAnnouncement_controller.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-models/services.js"></script>

protected/views/site/_listRural.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edgar
 * Date: 9/24/13
 * Time: 2:15 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<div class="left" ng-controller="ruralAnnouncementsController" ng-init="init();">
    <div cg-busy="{promise:promise,message:'loading',backdrop:true,}" style="height: 700px;">

        <?php echo $this->renderPartial('_listTemplate',array('title'=>$title, 'detail_url'=>$detail_url , 'isCar' =>$isCar )); ?>

    </div>
</div>

<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-controllers/listRuralAnnouncements.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-models/services.js"></script>

protected/views/site/_listTourism.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Edgar
 * Date: 9/28/13
 * Time: 9:10 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<div class="left" ng-controller="tourismAnnouncements_controller" ng-init="init();">
    <div cg-busy="{promise:promise,message:'loading',backdrop:true,}" style="height: 700px;">

        <?php echo $this->renderPartial('_listTemplate',array('title'=>$title, 'detail_url'=>$detail_url , 'isCar' =>$isCar )); ?>

    </div>
</div>

<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-controllers/listTourismAnnouncements_controller.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl; ?>/js/ng-models/services.js"></script>

protected/views/site/add_announcement.php
<div class="add_announcement right decoration">
    <div class="title"><h3 class="add_anonc_title"><?php echo Messages::getMessage(220); ?> </h3></div>
    <ul class="mt30">

        <?php if(!$this->isDealer()): ?>
            <li class="fm1"><?php echo CHtml::Link(Messages::getMessage(83),Yii::app()->createUrl( 'site/auto' ));?></li>
            <li class="fm2"><?php echo CHtml::Link(Messages::getMessage(86),Yii::app()->createUrl( 'site/autoRent' ));?></li>
            <li class="fm3"><?php echo CHtml::Link(Messages::getMessage(84),Yii::app()->createUrl( 'site/sparePartWheels' ));?></li>
            <li class="fm4"><?php echo CHtml::Link(Messages::getMessage(85),Yii::app()->createUrl( 'site/sparePart' ));?></li>
<!--            <li>--><?php //echo CHtml::Link(Messages::getMessage(87),Yii::app()->createUrl( 'site/autoService' ));?><!--</li>//-->
            <li class="fm5"><?php echo CHtml::Link(Messages::getMessage(88),Yii::app()->createUrl( 'site/ruralTech' ));?></li>
<!--            <li>--><?php //echo CHtml::Link(Messages::getMessage(89),Yii::app()->createUrl( 'site/shipping' ));?><!--</li>-->
<!--            <li class="fm"><img src="--><?php //echo Yii::app()->request->baseUrl; ?><!--/images/application-icon.png"/>--><?php //echo CHtml::Link(Messages::getMessage(90),Yii::app()->createUrl( 'site/transportation' ));?><!--</li>-->
<!--            <li>--><?php //echo CHtml::Link(Messages::getMessage(91),Yii::app()->createUrl( 'site/tourism' ));?><!--</li>//-->
            <li class="fm6"><?php echo CHtml::Link(Messages::getMessage(92),Yii::app()->createUrl( 'site/evacuator' ));?></li>
            <li class="fm7"><?php echo CHtml::Link(Messages::getMessage(93),Yii::app()->createUrl( 'site/taxi' ));?></li>
<!--            <li>--><?php //echo CHtml::Link(Messages::getMessage(94),Yii::app()->createUrl( 'site/trainingCar' ));?><!--</li>//-->
<!--            <li>--><?php //echo CHtml::Link(Messages::getMessage(95),Yii::app()->createUrl( 'site/jobForm' ));?><!--</li>//-->
        <?php endif ?>

        <?php if($this->isDealer()): ?>
            <li><?php echo CHtml::Link(Messages::getMessage(83),Yii::app()->createUrl( 'site/auto' ));?></li>
        <?php endif ?>
    </ul>
</div>
<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/js/jQueryRotate.js"></script>
<script type="text/javascript">
    jQuery(".fm img").rotate({
        bind:
        {
            mouseover : function() {
                jQuery(this).rotate({animateTo:120})
            },
            mouseout : function() {
                jQuery(this).rotate({animateTo:0})
            }
        }
    });
</script>
<script type="text/javascript">
$(document).ready(function(){
   $(".fm a").click(function(){
      $(".fm").clone()
          .css({'position':'absolute', 'z-index':'10000', 'left':$(".fm").offset()['left'], 'top':$(".fm").offset()['top']})
          .prependTo('.book')
          .animate({opacity:0.9,
          left:$(".book").offset()['left'],
          top:$(".book").offset()['top'],
              width:120,
              height:35
          },
          1000, function(){
              $(this).remove();
          });
   });
});
</script>

protected/views/site/successfullyAdded.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: Yerem
 * Date: 1/6/14
 * Time: 11:23 PM
 * To change this template use File | Settings | File Templates.
 */
?>
<div class="add_announcement right decoration">
    <div class="title"><h3 class="add_anonc_title" style="text-align: center;"><?php echo Messages::getMessage(324) ?></h3></div>
    <h2 class="h2" ><?php echo Messages::getMessage(37) ?></h2>
</div>